# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msgProtoBuf.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msgProtoBuf.proto',
  package='messages',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11msgProtoBuf.proto\x12\x08messages\"R\n\x13ServerResponse_load\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02ra\x18\x02 \x01(\t\x12!\n\x19\x64iffie_hellman_public_key\x18\x03 \x01(\t\"0\n\x14ServerResponse_shell\x12\n\n\x02rb\x18\x01 \x02(\t\x12\x0c\n\x04load\x18\x02 \x02(\x0c\"+\n\x0f\x43lientChallenge\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\n\n\x02ra\x18\x02 \x02(\t\"M\n\x0e\x43lientResponse\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\n\n\x02rb\x18\x02 \x02(\t\x12!\n\x19\x64iffie_hellman_public_key\x18\x03 \x02(\t\"\x1e\n\x0eGeneralMessage\x12\x0c\n\x04load\x18\x01 \x02(\t\">\n\x07Payload\x12\x0c\n\x04load\x18\x01 \x02(\x0c\x12\x0c\n\x04type\x18\x02 \x02(\t\x12\x17\n\x0f\x61uthMessageType\x18\x04 \x02(\t'
)




_SERVERRESPONSE_LOAD = _descriptor.Descriptor(
  name='ServerResponse_load',
  full_name='messages.ServerResponse_load',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='messages.ServerResponse_load.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ra', full_name='messages.ServerResponse_load.ra', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='diffie_hellman_public_key', full_name='messages.ServerResponse_load.diffie_hellman_public_key', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=113,
)


_SERVERRESPONSE_SHELL = _descriptor.Descriptor(
  name='ServerResponse_shell',
  full_name='messages.ServerResponse_shell',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rb', full_name='messages.ServerResponse_shell.rb', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='load', full_name='messages.ServerResponse_shell.load', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=163,
)


_CLIENTCHALLENGE = _descriptor.Descriptor(
  name='ClientChallenge',
  full_name='messages.ClientChallenge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='messages.ClientChallenge.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ra', full_name='messages.ClientChallenge.ra', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=208,
)


_CLIENTRESPONSE = _descriptor.Descriptor(
  name='ClientResponse',
  full_name='messages.ClientResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='messages.ClientResponse.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rb', full_name='messages.ClientResponse.rb', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='diffie_hellman_public_key', full_name='messages.ClientResponse.diffie_hellman_public_key', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=287,
)


_GENERALMESSAGE = _descriptor.Descriptor(
  name='GeneralMessage',
  full_name='messages.GeneralMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='load', full_name='messages.GeneralMessage.load', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=289,
  serialized_end=319,
)


_PAYLOAD = _descriptor.Descriptor(
  name='Payload',
  full_name='messages.Payload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='load', full_name='messages.Payload.load', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='messages.Payload.type', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='authMessageType', full_name='messages.Payload.authMessageType', index=2,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=321,
  serialized_end=383,
)

DESCRIPTOR.message_types_by_name['ServerResponse_load'] = _SERVERRESPONSE_LOAD
DESCRIPTOR.message_types_by_name['ServerResponse_shell'] = _SERVERRESPONSE_SHELL
DESCRIPTOR.message_types_by_name['ClientChallenge'] = _CLIENTCHALLENGE
DESCRIPTOR.message_types_by_name['ClientResponse'] = _CLIENTRESPONSE
DESCRIPTOR.message_types_by_name['GeneralMessage'] = _GENERALMESSAGE
DESCRIPTOR.message_types_by_name['Payload'] = _PAYLOAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServerResponse_load = _reflection.GeneratedProtocolMessageType('ServerResponse_load', (_message.Message,), {
  'DESCRIPTOR' : _SERVERRESPONSE_LOAD,
  '__module__' : 'msgProtoBuf_pb2'
  # @@protoc_insertion_point(class_scope:messages.ServerResponse_load)
  })
_sym_db.RegisterMessage(ServerResponse_load)

ServerResponse_shell = _reflection.GeneratedProtocolMessageType('ServerResponse_shell', (_message.Message,), {
  'DESCRIPTOR' : _SERVERRESPONSE_SHELL,
  '__module__' : 'msgProtoBuf_pb2'
  # @@protoc_insertion_point(class_scope:messages.ServerResponse_shell)
  })
_sym_db.RegisterMessage(ServerResponse_shell)

ClientChallenge = _reflection.GeneratedProtocolMessageType('ClientChallenge', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTCHALLENGE,
  '__module__' : 'msgProtoBuf_pb2'
  # @@protoc_insertion_point(class_scope:messages.ClientChallenge)
  })
_sym_db.RegisterMessage(ClientChallenge)

ClientResponse = _reflection.GeneratedProtocolMessageType('ClientResponse', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTRESPONSE,
  '__module__' : 'msgProtoBuf_pb2'
  # @@protoc_insertion_point(class_scope:messages.ClientResponse)
  })
_sym_db.RegisterMessage(ClientResponse)

GeneralMessage = _reflection.GeneratedProtocolMessageType('GeneralMessage', (_message.Message,), {
  'DESCRIPTOR' : _GENERALMESSAGE,
  '__module__' : 'msgProtoBuf_pb2'
  # @@protoc_insertion_point(class_scope:messages.GeneralMessage)
  })
_sym_db.RegisterMessage(GeneralMessage)

Payload = _reflection.GeneratedProtocolMessageType('Payload', (_message.Message,), {
  'DESCRIPTOR' : _PAYLOAD,
  '__module__' : 'msgProtoBuf_pb2'
  # @@protoc_insertion_point(class_scope:messages.Payload)
  })
_sym_db.RegisterMessage(Payload)


# @@protoc_insertion_point(module_scope)
